# Generated by Django 4.1.1 on 2022-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="_created",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="_deleted",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="_updated",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
