# Generated by Django 4.1.1 on 2022-10-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("D", "DISABLE"), ("E", "ENABLE")], default="E", max_length=10
            ),
        ),
    ]
