# Generated by Django 4.1.1 on 2022-10-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_product_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.CharField(blank=True, max_length=255, null=True)),
                ("_updated", models.CharField(blank=True, max_length=255, null=True)),
                ("_deleted", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.FloatField(default=0.0)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("COD", "COD"), ("BANKING", "BANKING")],
                        default="COD",
                        max_length=10,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("DONE", "DONE")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "_updater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_user_fk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.CharField(blank=True, max_length=255, null=True)),
                ("_updated", models.CharField(blank=True, max_length=255, null=True)),
                ("_deleted", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField()),
                (
                    "_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewi_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "_updater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_order_fk",
                        to="api.order",
                    ),
                ),
            ],
        ),
    ]
