# Generated by Django 4.1.1 on 2022-10-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_order_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created", models.CharField(blank=True, max_length=255, null=True)),
                ("_updated", models.CharField(blank=True, max_length=255, null=True)),
                ("_deleted", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "_updater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_order_fk",
                        to="api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_product_details",
                        to="api.product",
                    ),
                ),
            ],
        ),
    ]
