from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    UserView,
    LogoutView,
    UpdateUserView,
    UpdatePasswordView,
    ProductsAPIView,
    SingleProductAPIView,
    CategoriesAPIView,
    SingleCategoryAPIView,
    OrderAPIView,
    OrderDetailAPIView,
    CartsAPIView,
    SingleCartAPIView,
    GetProductOnCartAPIView,
)

urlpatterns = [
    path('user/register', RegisterView.as_view()),
    path('user/login', LoginView.as_view()),
    path('user/view', UserView.as_view()),
    path('user/logout', LogoutView.as_view()),
    path('user/update', UpdateUserView.as_view()),
    path('user/update/password', UpdatePasswordView.as_view()),
    path('product', ProductsAPIView.as_view()),
    path('product/<str:id>', SingleProductAPIView.as_view()),
    path('category', CategoriesAPIView.as_view()),
    path('category/<str:id>', SingleCategoryAPIView.as_view()),
    path('order', OrderAPIView.as_view()),
    path('order/<int:order_id>', OrderDetailAPIView.as_view()),
    path('cart', CartsAPIView.as_view()),
    path('cart/<int:cart_id>', SingleCartAPIView.as_view()),
    path('cart/product/<int:product_id>', GetProductOnCartAPIView.as_view()),
]